name: parquet_duckdb_demo
version: "1.0.0"
config-version: 2

profile: parquet_duckdb_demo

model-paths: ["models"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  parquet_duckdb_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
